spring.application.name=expense-tracker
spring.datasource.url=jdbc:mysql://zephyr.proxy.rlwy.net:25337/railway
spring.datasource.username=root
spring.datasource.password=SbSZprUTaRXQYdEafnNTIVWmhtVUNVHF

spring.jpa.hibernate.ddl-auto=update